import { StyleSheet } from 'react-native';

export const getStyles = (theme: any) => {
  const isDark = theme.colors.background.primary === '#1e1226';

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: isDark ? '#171627' : '#FFFFFF',
      padding: 16,
    },
    inicio: {
      fontSize: 22,
      fontWeight: 'bold',
      color: isDark ? '#0C8BEA' : '#1E4789',
      marginTop: 10,
    },
    avatarSessao: {
      alignItems: 'center',
      marginVertical: 20,
      position: 'relative',
    },
    avatar: {
      width: 100,
      height: 100,
      borderRadius: 50,
      borderWidth: 2,
      borderColor: isDark ? '#1EBFDB' : '#1E4789',
    },
    editAvatar: {
      position: 'absolute',
      bottom: 0,
      right: 130,
      backgroundColor: isDark ? '#4E3592' : '#B3C7F9',
      borderRadius: 20,
      padding: 6,
      borderWidth: 1,
      borderColor: isDark ? '#1EBFDB' : '#1E4789',
    },
    name: {
      fontSize: 18,
      fontWeight: '600',
      color: isDark ? '#FFFFFF' : '#1A1A1A',
      textAlign: 'center',
    },
    email: {
      fontSize: 14,
      color: isDark ? '#FFFFFF' : '#333333',
      textAlign: 'center',
      marginBottom: 20,
    },
    acoes: {
      backgroundColor: isDark ? '#4E3592' : '#DDE6FF',
      padding: 12,
      borderRadius: 12,
      marginBottom: 20,
    },
    acaoBotao: {
      backgroundColor: isDark ? '#1EBFDB' : '#5C8EF2', 
      padding: 10,
      borderRadius: 10,
      marginBottom: 10,
    },
    acaoTexto: {
      color: isDark ? '#0F0F0F' : '#FFFFFF',
      fontWeight: 'bold',
      textAlign: 'center',
    },
    title: {
      fontSize: 16,
      fontWeight: 'bold',
      color: isDark ? '#0C8BEA' : '#1E4789',
      marginTop: 20,
      marginBottom: 10,
    },
    playlistCard: {
      flexDirection: 'row',
      backgroundColor: isDark ? '#4E3592' : '#E8EDFF',
      borderRadius: 20,
      padding: 10,
      marginBottom: 15,
    },
    playlistName: {
      color: isDark ? '#FFFFFF' : '#1A1A1A',
      fontWeight: '600',
      fontSize: 14,
    },
    status: {
      backgroundColor: isDark ? '#0C8BEA' : '#B3C7F9',
      borderRadius: 14,
      padding: 14,
      marginBottom: 20,
    },
    statusTexto: {
      color: isDark ? '#FFFFFF' : '#1A1A1A',
      fontSize: 14,
      marginBottom: 6,
      fontWeight: '500',
    },
    exportarBotao: {
      backgroundColor: isDark ? '#1EBFDB' : '#5C8EF2',
      padding: 12,
      borderRadius: 10,
      alignItems: 'center',
      marginBottom: 20,
    },
    exportarTexto: {
      color: isDark ? '#0F0F0F' : '#FFFFFF',
      fontWeight: 'bold',
    },
    avancado: {
      backgroundColor: isDark ? '#4E3592' : '#DDE6FF',
      padding: 10,
      borderRadius: 10,
      marginBottom: 10,
    },
    avancadoTexto: {
      color: isDark ? '#FFFFFF' : '#1A1A1A',
      textAlign: 'center',
    },
    manchasContainer: {
      position: 'absolute',
      width: '100%',
      height: '100%',
      zIndex: -1,
    },
    manchaRoxa: {
      position: 'absolute',
      top: 80,
      left: -100,
      width: 350,
      height: 300,
      backgroundColor: '#4E3592',
      borderTopLeftRadius: 180,
      borderTopRightRadius: 60,
      borderBottomLeftRadius: 80,
      borderBottomRightRadius: 200,
      opacity: 0.3,
      transform: [{ rotate: '25deg' }],
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 10,
    },

    manchaAzul: {
      position: 'absolute',
      top: 400,
      right: -120,
      width: 300,
      height: 270,
      backgroundColor: '#1EBFDB',
      borderTopLeftRadius: 140,
      borderTopRightRadius: 190,
      borderBottomLeftRadius: 100,
      borderBottomRightRadius: 50,
      opacity: 0.25,
      transform: [{ rotate: '-30deg' }],
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 10,
    },
    botaoEngrenagem: {
      position: 'absolute',
      bottom: 25,
      left: 20,
      backgroundColor: '#1EBFDB',
      borderRadius: 30,
      padding: 12,
      zIndex: 10,
      elevation: 6,
    },
    playlistImg: {
      width: 40,
      height: 40,
      borderRadius: 10,
      marginRight: 10,
    },
    logoutButton: {
      position: 'absolute',
      top: 40,
      right: 20,
      zIndex: 10,
    },
    menuConfig: {
      position: 'absolute',
      bottom: 80,
      left: 20,
      backgroundColor: '#1EBFDB',
      borderRadius: 12,
      paddingVertical: 10,
      paddingHorizontal: 12,
      zIndex: 15,
      elevation: 10,
      width: 200,
    },

    menuItem: {
      paddingVertical: 8,
    },

    menuText: {
      color: '#0F0F0F',
      fontWeight: '600',
    },
    boxContainer: {
      borderRadius: 16,
      padding: 16,
      marginBottom: 20,
      overflow: 'hidden', 
    },
    boxTitle: {
      color: '#1EBFDB',
      fontWeight: 'bold',
      fontSize: 18,
      marginBottom: 12,
    },
  });
};